### ISSUE TITLE
License file in repo & npm package

### ISSUE THREAD

**Issue by dariagrudzien** [estools/esrecurse#20]
@Constellation Hi Yusuke, thank you for this package. Would you mind adding the license file to the repo & the npm package? Without it we're not really able to use it, because it makes the npm package a distribution of proprietary code.

Many thanks.

**Comment by lotusorrose** [comment]
the license is in the readme, but I agree a separate license file would help

**Comment by lotusorrose** [comment]
https://github.com/estools/esrecurse/pull/25

**Comment by michaelficarra** [comment]
In addition to the license already being in the README, it is described [in the `package.json`](https://github.com/estools/esrecurse/blob/8ceb63797813d9ac69572a671b95cf58ffdf35b6/package.json#L41). This seems to be sufficient for the roughly 23,673,464 weekly users. I'm unconvinced that we need to distribute an additional license file.

**Comment by lotusorrose** [comment]
sure that works for human consumption, however tools like `yarn licenses generate-disclaimer` do not get the correct license. 
(on a side note all downloads may not be distinct users, quite likely CI/CD pipelines would counted in the downloads, nor would all the actual users actually publish a 3rd party license document with the actual license for their products. folks like me who need to publish the document manually copy paste the text since tools cannot do that for this repo) 
Feel free to close the issue and the pull request if you are still unconvinced.

**Comment by michaelficarra** [comment]
Fixed by #25.
